# ============================================================================
# configs/speech/my_run/search-space.yaml - HPO search space (brain_magic_no_feature_encoder)
# ============================================================================

'("general", "seed")' : [1]
'("model", "brain_magic_no_feature_encoder", "input_dim")' : [57]
'("model", "brain_magic_no_feature_encoder", "attention_dim")' : [128]
'("model", "brain_magic_no_feature_encoder", "output_dim")' : [1]
'("model", "brain_magic_no_feature_encoder", "kernel_size")' : [40]
'("model", "brain_magic_no_feature_encoder", "depthwise_kernel")' : [30]
'("model", "brain_magic_no_feature_encoder", "n_subjects")' : [25]
'("model", "brain_magic_no_feature_encoder", "num_blocks1")' : [8]
'("model", "brain_magic_no_feature_encoder", "num_blocks2")' : [19]
'("model", "brain_magic_no_feature_encoder", "dropout")' : [0.1]
'("loss", "config", "weight")' : [[1.0, 1.0]]
'("general", "loss_type")' : ['mse']
'("optimizer", "config", "lr")' : [0.001]
'("data", "datasets", "train", 0, "eeg_speech_v1", "tmax")' : [12.0]
