data:
  datasets:
    train:
      - speech_v1:
          data_path: '/gpfs/share/home/2201112028/libribrain_data'
          preprocessing_str: 'bads+headpos+sss+notch+bp+ds'
          standardize: true
          tmin: 0.0
          tmax: 12.0
          exclude_run_keys: [['0', '11', 'Sherlock1', '2'], 
                             ['0', '12', 'Sherlock1', '2'],
                            ]
          preload_files: false
          download: false
          delay: 0
          data_type: 'train'

          
    val:
      - speech_v1:
          data_path: '/gpfs/share/home/2201112028/libribrain_data'
          standardize: true
          tmin: 0.0
          tmax: 12.0
          include_run_keys: [['0', '11', 'Sherlock1', '2']]
          preload_files: false
          download: false
          delay: 0
          data_type: 'val'
    test:
      - speech_v1:
          data_path: '/gpfs/share/home/2201112028/libribrain_data'
          standardize: true
          tmin: 0.0
          tmax: 12.0
          include_run_keys: [['0', '12', 'Sherlock1', '2']]
          preload_files: false
          download: false
          delay: 0
          data_type: 'test'
  dataloader: 
    batch_size: 64
    num_workers: 4
  general:
    inMemory: False
    #train_fraction: 0.003
    #val_fraction: 0.01


model:
  brain_magic_speech_v7:
      input_dim: 204
      attention_dim: 128
      output_dim: 1
      kernel_size: 40
      dropout: 0.1
      depthwise_kernel: 30
      num_blocks1: 8
      num_blocks2: 19

loss:
  config:
    weight: 
    - 1.0
    - 1.0
  
  
optimizer:
  name: adamw
  config:
    lr: 0.001
    
trainer:
  max_epochs: 100

general:
  tensorboard: False
  output_path: 'results'
  model_name: "brain_magic_speech_v7"
  dataset_name: “speech_v1”
  project_name: "speech-detection"
  seed: 42    # 模型初始化种子
  split_seed: 46  # 数据划分种子
  threshold: [0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2, 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3, 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4, 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5, 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6, 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7, 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8, 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9, 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]
  loss_type: 'mse'
  add: 'v1'
  margin_weight: [0.1, 0.1]
