'("general", "seed")' : [42]
'("general", "split_seed")' : [42, 43, 44, 45, 46]
'("model", "brain_magic_speech_v7", "input_dim")' : [204]
'("model", "brain_magic_speech_v7", "attention_dim")' : [128]
'("model", "brain_magic_speech_v7", "output_dim")' : [1]
'("model", "brain_magic_speech_v7", "kernel_size")' : [40]
'("model", "brain_magic_speech_v7", "depthwise_kernel")' : [30]
'("model", "brain_magic_speech_v7", "num_blocks1")' : [8]
'("model", "brain_magic_speech_v7", "num_blocks2")' : [19]
'("model", "brain_magic_speech_v7", "dropout")' : [0.1]
'("loss", "config", "weight")' : [[1.0,1.0]]
'("general", "loss_type")' : ['mse']
'("optimizer", "config", "lr")' : [0.001]
